### ISSUE TITLE
Should poetry create new environment in local `.venv` directory by default?

### ISSUE THREAD

**Issue by dartt0n** [dartt0n/poetry-machine-learning-starter#1]
Poetry can be configured to utilize `.venv` directory, similar to `python3 -m venv .venv` command. Should this behaviour be default for this template?

`poetry.toml`:
```toml
[virtualenvs]
in-project = true
path = ".venv"
```
